import 'country.dart';

class CountryConstants {
  static const List<Country> countries = [
    Country(code: 'AF', name: 'Afghanistan', flag: '🇦🇫', timezone: 'Asia/Kabul'),
    Country(code: 'AL', name: 'Albania', flag: '🇦🇱', timezone: 'Europe/Tirane'),
    Country(code: 'DZ', name: 'Algeria', flag: '🇩🇿', timezone: 'Africa/Algiers'),
    Country(code: 'AS', name: 'American Samoa', flag: '🇦🇸', timezone: 'Pacific/Pago_Pago'),
    Country(code: 'AD', name: 'Andorra', flag: '🇦🇩', timezone: 'Europe/Andorra'),
    Country(code: 'AO', name: 'Angola', flag: '🇦🇴', timezone: 'Africa/Luanda'),
    Country(code: 'AI', name: 'Anguilla', flag: '🇦🇮', timezone: 'America/Anguilla'),
    Country(code: 'AQ', name: 'Antarctica', flag: '🇦🇶', timezone: 'Antarctica/McMurdo'),
    Country(code: 'AG', name: 'Antigua and Barbuda', flag: '🇦🇬', timezone: 'America/Antigua'),
    Country(code: 'AR', name: 'Argentina', flag: '🇦🇷', timezone: 'America/Argentina/Buenos_Aires'),
    Country(code: 'AM', name: 'Armenia', flag: '🇦🇲', timezone: 'Asia/Yerevan'),
    Country(code: 'AW', name: 'Aruba', flag: '🇦🇼', timezone: 'America/Aruba'),
    Country(code: 'AU', name: 'Australia', flag: '🇦🇺', timezone: 'Australia/Sydney'),
    Country(code: 'AT', name: 'Austria', flag: '🇦🇹', timezone: 'Europe/Vienna'),
    Country(code: 'AZ', name: 'Azerbaijan', flag: '🇦🇿', timezone: 'Asia/Baku'),
    Country(code: 'BS', name: 'Bahamas', flag: '🇧🇸', timezone: 'America/Bahamas'),
    Country(code: 'BH', name: 'Bahrain', flag: '🇧🇭', timezone: 'Asia/Bahrain'),
    Country(code: 'BD', name: 'Bangladesh', flag: '🇧🇩', timezone: 'Asia/Dhaka'),
    Country(code: 'BB', name: 'Barbados', flag: '🇧🇧', timezone: 'America/Barbados'),
    Country(code: 'BY', name: 'Belarus', flag: '🇧🇾', timezone: 'Europe/Minsk'),
    Country(code: 'BE', name: 'Belgium', flag: '🇧🇪', timezone: 'Europe/Brussels'),
    Country(code: 'BZ', name: 'Belize', flag: '🇧🇿', timezone: 'America/Belize'),
    Country(code: 'BJ', name: 'Benin', flag: '🇧🇯', timezone: 'Africa/Porto-Novo'),
    Country(code: 'BM', name: 'Bermuda', flag: '🇧🇲', timezone: 'Atlantic/Bermuda'),
    Country(code: 'BT', name: 'Bhutan', flag: '🇧🇹', timezone: 'Asia/Thimphu'),
    Country(code: 'BO', name: 'Bolivia', flag: '🇧🇴', timezone: 'America/La_Paz'),
    Country(code: 'BA', name: 'Bosnia and Herzegovina', flag: '🇧🇦', timezone: 'Europe/Sarajevo'),
    Country(code: 'BW', name: 'Botswana', flag: '🇧🇼', timezone: 'Africa/Gaborone'),
    Country(code: 'BR', name: 'Brazil', flag: '🇧🇷', timezone: 'America/Sao_Paulo'),
    Country(code: 'BN', name: 'Brunei Darussalam', flag: '🇧🇳', timezone: 'Asia/Brunei'),
    Country(code: 'BG', name: 'Bulgaria', flag: '🇧🇬', timezone: 'Europe/Sofia'),
    Country(code: 'BF', name: 'Burkina Faso', flag: '🇧🇫', timezone: 'Africa/Ouagadougou'),
    Country(code: 'BI', name: 'Burundi', flag: '🇧🇮', timezone: 'Africa/Bujumbura'),
    Country(code: 'KH', name: 'Cambodia', flag: '🇰🇭', timezone: 'Asia/Phnom_Penh'),
    Country(code: 'CM', name: 'Cameroon', flag: '🇨🇲', timezone: 'Africa/Douala'),
    Country(code: 'CA', name: 'Canada', flag: '🇨🇦', timezone: 'America/Toronto'),
    Country(code: 'CV', name: 'Cape Verde', flag: '🇨🇻', timezone: 'Atlantic/Cape_Verde'),
    Country(code: 'KY', name: 'Cayman Islands', flag: '🇰🇾', timezone: 'America/Cayman'),
    Country(code: 'CF', name: 'Central African Republic', flag: '🇨🇫', timezone: 'Africa/Bangui'),
    Country(code: 'TD', name: 'Chad', flag: '🇹🇩', timezone: 'Africa/Ndjamena'),
    Country(code: 'CL', name: 'Chile', flag: '🇨🇱', timezone: 'America/Santiago'),
    Country(code: 'CN', name: 'China', flag: '🇨🇳', timezone: 'Asia/Shanghai'),
    Country(code: 'CO', name: 'Colombia', flag: '🇨🇴', timezone: 'America/Bogota'),
    Country(code: 'KM', name: 'Comoros', flag: '🇰🇲', timezone: 'Indian/Comoro'),
    Country(code: 'CG', name: 'Congo', flag: '🇨🇬', timezone: 'Africa/Brazzaville'),
    Country(code: 'CD', name: 'Congo, Democratic Republic of the', flag: '🇨🇩', timezone: 'Africa/Kinshasa'),
    Country(code: 'CK', name: 'Cook Islands', flag: '🇨🇰', timezone: 'Pacific/Rarotonga'),
    Country(code: 'CR', name: 'Costa Rica', flag: '🇨🇷', timezone: 'America/Costa_Rica'),
    Country(code: 'CI', name: 'Cote d\'Ivoire', flag: '🇨🇮', timezone: 'Africa/Abidjan'),
    Country(code: 'HR', name: 'Croatia', flag: '🇭🇷', timezone: 'Europe/Zagreb'),
    Country(code: 'CU', name: 'Cuba', flag: '🇨🇺', timezone: 'America/Havana'),
    Country(code: 'CY', name: 'Cyprus', flag: '🇨🇾', timezone: 'Asia/Nicosia'),
    Country(code: 'CZ', name: 'Czech Republic', flag: '🇨🇿', timezone: 'Europe/Prague'),
    Country(code: 'DK', name: 'Denmark', flag: '🇩🇰', timezone: 'Europe/Copenhagen'),
    Country(code: 'DJ', name: 'Djibouti', flag: '🇩🇯', timezone: 'Africa/Djibouti'),
    Country(code: 'DM', name: 'Dominica', flag: '🇩🇲', timezone: 'America/Dominica'),
    Country(code: 'DO', name: 'Dominican Republic', flag: '🇩🇴', timezone: 'America/Santo_Domingo'),
    Country(code: 'EC', name: 'Ecuador', flag: '🇪🇨', timezone: 'America/Guayaquil'),
    Country(code: 'EG', name: 'Egypt', flag: '🇪🇬', timezone: 'Africa/Cairo'),
    Country(code: 'SV', name: 'El Salvador', flag: '🇸🇻', timezone: 'America/El_Salvador'),
    Country(code: 'GQ', name: 'Equatorial Guinea', flag: '🇬🇶', timezone: 'Africa/Malabo'),
    Country(code: 'ER', name: 'Eritrea', flag: '🇪🇷', timezone: 'Africa/Asmara'),
    Country(code: 'EE', name: 'Estonia', flag: '🇪🇪', timezone: 'Europe/Tallinn'),
    Country(code: 'ET', name: 'Ethiopia', flag: '🇪🇹', timezone: 'Africa/Addis_Ababa'),
    Country(code: 'FK', name: 'Falkland Islands (Malvinas)', flag: '🇫🇰', timezone: 'Atlantic/Stanley'),
    Country(code: 'FO', name: 'Faroe Islands', flag: '🇫🇴', timezone: 'Atlantic/Faroe'),
    Country(code: 'FJ', name: 'Fiji', flag: '🇫🇯', timezone: 'Pacific/Fiji'),
    Country(code: 'FI', name: 'Finland', flag: '🇫🇮', timezone: 'Europe/Helsinki'),
    Country(code: 'FR', name: 'France', flag: '🇫🇷', timezone: 'Europe/Paris'),
    Country(code: 'GF', name: 'French Guiana', flag: '🇬🇫', timezone: 'America/Cayenne'),
    Country(code: 'PF', name: 'French Polynesia', flag: '🇵🇫', timezone: 'Pacific/Tahiti'),
    Country(code: 'GA', name: 'Gabon', flag: '🇬🇦', timezone: 'Africa/Libreville'),
    Country(code: 'GM', name: 'Gambia', flag: '🇬🇲', timezone: 'Africa/Banjul'),
    Country(code: 'GE', name: 'Georgia', flag: '🇬🇪', timezone: 'Asia/Tbilisi'),
    Country(code: 'DE', name: 'Germany', flag: '🇩🇪', timezone: 'Europe/Berlin'),
    Country(code: 'GH', name: 'Ghana', flag: '🇬🇭', timezone: 'Africa/Accra'),
    Country(code: 'GI', name: 'Gibraltar', flag: '🇬🇮', timezone: 'Europe/Gibraltar'),
    Country(code: 'GR', name: 'Greece', flag: '🇬🇷', timezone: 'Europe/Athens'),
    Country(code: 'GL', name: 'Greenland', flag: '🇬🇱', timezone: 'America/Godthab'),
    Country(code: 'GD', name: 'Grenada', flag: '🇬🇩', timezone: 'America/Grenada'),
    Country(code: 'GP', name: 'Guadeloupe', flag: '🇬🇵', timezone: 'America/Marigot'),
    Country(code: 'GU', name: 'Guam', flag: '🇬🇺', timezone: 'Pacific/Guam'),
    Country(code: 'GT', name: 'Guatemala', flag: '🇬🇹', timezone: 'America/Guatemala'),
    Country(code: 'GG', name: 'Guernsey', flag: '🇬🇬', timezone: 'Europe/Guernsey'),
    Country(code: 'GN', name: 'Guinea', flag: '🇬🇳', timezone: 'Africa/Conakry'),
    Country(code: 'GW', name: 'Guinea-Bissau', flag: '🇬🇼', timezone: 'Africa/Bissau'),
    Country(code: 'GY', name: 'Guyana', flag: '🇬🇾', timezone: 'America/Guyana'),
    Country(code: 'HT', name: 'Haiti', flag: '🇭🇹', timezone: 'America/Port-au-Prince'),
    Country(code: 'VA', name: 'Holy See (Vatican City State)', flag: '🇻🇦', timezone: 'Europe/Vatican'),
    Country(code: 'HN', name: 'Honduras', flag: '🇭🇳', timezone: 'America/Tegucigalpa'),
    Country(code: 'HK', name: 'Hong Kong', flag: '🇭🇰', timezone: 'Asia/Hong_Kong'),
    Country(code: 'HU', name: 'Hungary', flag: '🇭🇺', timezone: 'Europe/Budapest'),
    Country(code: 'IS', name: 'Iceland', flag: '🇮🇸', timezone: 'Atlantic/Reykjavik'),
    Country(code: 'IN', name: 'India', flag: '🇮🇳', timezone: 'Asia/Kolkata'),
    Country(code: 'ID', name: 'Indonesia', flag: '🇮🇩', timezone: 'Asia/Jakarta'),
    Country(code: 'IR', name: 'Iran, Islamic Republic of', flag: '🇮🇷', timezone: 'Asia/Tehran'),
    Country(code: 'IQ', name: 'Iraq', flag: '🇮🇶', timezone: 'Asia/Baghdad'),
    Country(code: 'IE', name: 'Ireland', flag: '🇮🇪', timezone: 'Europe/Dublin'),
    Country(code: 'IM', name: 'Isle of Man', flag: '🇮🇲', timezone: 'Europe/Isle_of_Man'),
    Country(code: 'IL', name: 'Israel', flag: '🇮🇱', timezone: 'Asia/Jerusalem'),
    Country(code: 'IT', name: 'Italy', flag: '🇮🇹', timezone: 'Europe/Rome'),
    Country(code: 'JM', name: 'Jamaica', flag: '🇯🇲', timezone: 'America/Jamaica'),
    Country(code: 'JP', name: 'Japan', flag: '🇯🇵', timezone: 'Asia/Tokyo'),
    Country(code: 'JE', name: 'Jersey', flag: '🇯🇪', timezone: 'Europe/Jersey'),
    Country(code: 'JO', name: 'Jordan', flag: '🇯🇴', timezone: 'Asia/Amman'),
    Country(code: 'KZ', name: 'Kazakhstan', flag: '🇰🇿', timezone: 'Asia/Almaty'),
    Country(code: 'KE', name: 'Kenya', flag: '🇰🇪', timezone: 'Africa/Nairobi'),
    Country(code: 'KI', name: 'Kiribati', flag: '🇰🇮', timezone: 'Pacific/Tarawa'),
    Country(code: 'KP', name: 'Korea, Democratic People\'s Republic of', flag: '🇰🇵', timezone: 'Asia/Pyongyang'),
    Country(code: 'KR', name: 'Korea, Republic of', flag: '🇰🇷', timezone: 'Asia/Seoul'),
    Country(code: 'KW', name: 'Kuwait', flag: '🇰🇼', timezone: 'Asia/Kuwait'),
    Country(code: 'KG', name: 'Kyrgyzstan', flag: '🇰🇬', timezone: 'Asia/Bishkek'),
    Country(code: 'LA', name: 'Lao People\'s Democratic Republic', flag: '🇱🇦', timezone: 'Asia/Vientiane'),
    Country(code: 'LV', name: 'Latvia', flag: '🇱🇻', timezone: 'Europe/Riga'),
    Country(code: 'LB', name: 'Lebanon', flag: '🇱🇧', timezone: 'Asia/Beirut'),
    Country(code: 'LS', name: 'Lesotho', flag: '🇱🇸', timezone: 'Africa/Maseru'),
    Country(code: 'LR', name: 'Liberia', flag: '🇱🇷', timezone: 'Africa/Monrovia'),
    Country(code: 'LY', name: 'Libyan Arab Jamahiriya', flag: '🇱🇾', timezone: 'Africa/Tripoli'),
    Country(code: 'LI', name: 'Liechtenstein', flag: '🇱🇮', timezone: 'Europe/Vaduz'),
    Country(code: 'LT', name: 'Lithuania', flag: '🇱🇹', timezone: 'Europe/Vilnius'),
    Country(code: 'LU', name: 'Luxembourg', flag: '🇱🇺', timezone: 'Europe/Luxembourg'),
    Country(code: 'MO', name: 'Macao', flag: '🇲🇴', timezone: 'Asia/Macau'),
    Country(code: 'MK', name: 'Macedonia, the former Yugoslav Republic of', flag: '🇲🇰', timezone: 'Europe/Skopje'),
    Country(code: 'MG', name: 'Madagascar', flag: '🇲🇬', timezone: 'Indian/Antananarivo'),
    Country(code: 'MW', name: 'Malawi', flag: '🇲🇼', timezone: 'Africa/Blantyre'),
    Country(code: 'MY', name: 'Malaysia', flag: '🇲🇾', timezone: 'Asia/Kuala_Lumpur'),
    Country(code: 'MV', name: 'Maldives', flag: '🇲🇻', timezone: 'Indian/Maldives'),
    Country(code: 'ML', name: 'Mali', flag: '🇲🇱', timezone: 'Africa/Bamako'),
    Country(code: 'MT', name: 'Malta', flag: '🇲🇹', timezone: 'Europe/Malta'),
    Country(code: 'MH', name: 'Marshall Islands', flag: '🇲🇭', timezone: 'Pacific/Majuro'),
    Country(code: 'MQ', name: 'Martinique', flag: '🇲🇶', timezone: 'America/Martinique'),
    Country(code: 'MR', name: 'Mauritania', flag: '🇲🇷', timezone: 'Africa/Nouakchott'),
    Country(code: 'MU', name: 'Mauritius', flag: '🇲🇺', timezone: 'Indian/Mauritius'),
    Country(code: 'YT', name: 'Mayotte', flag: '🇾🇹', timezone: 'Indian/Mayotte'),
    Country(code: 'MX', name: 'Mexico', flag: '🇲🇽', timezone: 'America/Mexico_City'),
    Country(code: 'FM', name: 'Micronesia, Federated States of', flag: '🇫🇲', timezone: 'Pacific/Pohnpei'),
    Country(code: 'MD', name: 'Moldova, Republic of', flag: '🇲🇩', timezone: 'Europe/Chisinau'),
    Country(code: 'MC', name: 'Monaco', flag: '🇲🇨', timezone: 'Europe/Monaco'),
    Country(code: 'MN', name: 'Mongolia', flag: '🇲🇳', timezone: 'Asia/Ulaanbaatar'),
    Country(code: 'ME', name: 'Montenegro', flag: '🇲🇪', timezone: 'Europe/Podgorica'),
    Country(code: 'MS', name: 'Montserrat', flag: '🇲🇸', timezone: 'America/Montserrat'),
    Country(code: 'MA', name: 'Morocco', flag: '🇲🇦', timezone: 'Africa/Casablanca'),
    Country(code: 'MZ', name: 'Mozambique', flag: '🇲🇿', timezone: 'Africa/Maputo'),
    Country(code: 'MM', name: 'Myanmar', flag: '🇲🇲', timezone: 'Asia/Rangoon'),
    Country(code: 'NA', name: 'Namibia', flag: '🇳🇦', timezone: 'Africa/Windhoek'),
    Country(code: 'NR', name: 'Nauru', flag: '🇳🇷', timezone: 'Pacific/Nauru'),
    Country(code: 'NP', name: 'Nepal', flag: '🇳🇵', timezone: 'Asia/Katmandu'),
    Country(code: 'NL', name: 'Netherlands', flag: '🇳🇱', timezone: 'Europe/Amsterdam'),
    Country(code: 'NC', name: 'New Caledonia', flag: '🇳🇨', timezone: 'Pacific/Noumea'),
    Country(code: 'NZ', name: 'New Zealand', flag: '🇳🇿', timezone: 'Pacific/Auckland'),
    Country(code: 'NI', name: 'Nicaragua', flag: '🇳🇮', timezone: 'America/Managua'),
    Country(code: 'NE', name: 'Niger', flag: '🇳🇪', timezone: 'Africa/Niamey'),
    Country(code: 'NG', name: 'Nigeria', flag: '🇳🇬', timezone: 'Africa/Lagos'),
    Country(code: 'NU', name: 'Niue', flag: '🇳🇺', timezone: 'Pacific/Niue'),
    Country(code: 'NF', name: 'Norfolk Island', flag: '🇳🇫', timezone: 'Pacific/Norfolk'),
    Country(code: 'MP', name: 'Northern Mariana Islands', flag: '🇲🇵', timezone: 'Pacific/Saipan'),
    Country(code: 'NO', name: 'Norway', flag: '🇳🇴', timezone: 'Europe/Oslo'),
    Country(code: 'OM', name: 'Oman', flag: '🇴🇲', timezone: 'Asia/Muscat'),
    Country(code: 'PK', name: 'Pakistan', flag: '🇵🇰', timezone: 'Asia/Karachi'),
    Country(code: 'PW', name: 'Palau', flag: '🇵🇼', timezone: 'Pacific/Palau'),
    Country(code: 'PS', name: 'Palestinian Territory, Occupied', flag: '🇵🇸', timezone: 'Asia/Gaza'),
    Country(code: 'PA', name: 'Panama', flag: '🇵🇦', timezone: 'America/Panama'),
    Country(code: 'PG', name: 'Papua New Guinea', flag: '🇵🇬', timezone: 'Pacific/Port_Moresby'),
    Country(code: 'PY', name: 'Paraguay', flag: '🇵🇾', timezone: 'America/Asuncion'),
    Country(code: 'PE', name: 'Peru', flag: '🇵🇪', timezone: 'America/Lima'),
    Country(code: 'PH', name: 'Philippines', flag: '🇵🇭', timezone: 'Asia/Manila'),
    Country(code: 'PN', name: 'Pitcairn', flag: '🇵🇳', timezone: 'Pacific/Pitcairn'),
    Country(code: 'PL', name: 'Poland', flag: '🇵🇱', timezone: 'Europe/Warsaw'),
    Country(code: 'PT', name: 'Portugal', flag: '🇵🇹', timezone: 'Europe/Lisbon'),
    Country(code: 'PR', name: 'Puerto Rico', flag: '🇵🇷', timezone: 'America/Puerto_Rico'),
    Country(code: 'QA', name: 'Qatar', flag: '🇶🇦', timezone: 'Asia/Qatar'),
    Country(code: 'RE', name: 'Reunion', flag: '🇷🇪', timezone: 'Indian/Reunion'),
    Country(code: 'RO', name: 'Romania', flag: '🇷🇴', timezone: 'Europe/Bucharest'),
    Country(code: 'RU', name: 'Russian Federation', flag: '🇷🇺', timezone: 'Europe/Moscow'),
    Country(code: 'RW', name: 'Rwanda', flag: '🇷🇼', timezone: 'Africa/Kigali'),
    Country(code: 'BL', name: 'Saint Barthelemy', flag: '🇧🇱', timezone: 'America/St_Barthelemy'),
    Country(code: 'SH', name: 'Saint Helena', flag: '🇸🇭', timezone: 'Atlantic/St_Helena'),
    Country(code: 'KN', name: 'Saint Kitts and Nevis', flag: '🇰🇳', timezone: 'America/St_Kitts'),
    Country(code: 'LC', name: 'Saint Lucia', flag: '🇱🇨', timezone: 'America/St_Lucia'),
    Country(code: 'MF', name: 'Saint Martin', flag: '🇲🇫', timezone: 'America/Marigot'),
    Country(code: 'PM', name: 'Saint Pierre and Miquelon', flag: '🇵🇲', timezone: 'America/Miquelon'),
    Country(code: 'VC', name: 'Saint Vincent and the Grenadines', flag: '🇻🇨', timezone: 'America/St_Vincent'),
    Country(code: 'WS', name: 'Samoa', flag: '🇼🇸', timezone: 'Pacific/Apia'),
    Country(code: 'SM', name: 'San Marino', flag: '🇸🇲', timezone: 'Europe/San_Marino'),
    Country(code: 'ST', name: 'Sao Tome and Principe', flag: '🇸🇹', timezone: 'Africa/Sao_Tome'),
    Country(code: 'SA', name: 'Saudi Arabia', flag: '🇸🇦', timezone: 'Asia/Riyadh'),
    Country(code: 'SN', name: 'Senegal', flag: '🇸🇳', timezone: 'Africa/Dakar'),
    Country(code: 'RS', name: 'Serbia', flag: '🇷🇸', timezone: 'Europe/Belgrade'),
    Country(code: 'SC', name: 'Seychelles', flag: '🇸🇨', timezone: 'Indian/Mahe'),
    Country(code: 'SL', name: 'Sierra Leone', flag: '🇸🇱', timezone: 'Africa/Freetown'),
    Country(code: 'SG', name: 'Singapore', flag: '🇸🇬', timezone: 'Asia/Singapore'),
    Country(code: 'SK', name: 'Slovakia', flag: '🇸🇰', timezone: 'Europe/Bratislava'),
    Country(code: 'SI', name: 'Slovenia', flag: '🇸🇮', timezone: 'Europe/Ljubljana'),
    Country(code: 'SB', name: 'Solomon Islands', flag: '🇸🇧', timezone: 'Pacific/Guadalcanal'),
    Country(code: 'SO', name: 'Somalia', flag: '🇸🇴', timezone: 'Africa/Mogadishu'),
    Country(code: 'ZA', name: 'South Africa', flag: '🇿🇦', timezone: 'Africa/Johannesburg'),
    Country(code: 'GS', name: 'South Georgia and the South Sandwich Islands', flag: '🇬🇸', timezone: 'Atlantic/South_Georgia'),
    Country(code: 'ES', name: 'Spain', flag: '🇪🇸', timezone: 'Europe/Madrid'),
    Country(code: 'LK', name: 'Sri Lanka', flag: '🇱🇰', timezone: 'Asia/Colombo'),
    Country(code: 'SD', name: 'Sudan', flag: '🇸🇩', timezone: 'Africa/Khartoum'),
    Country(code: 'SR', name: 'Suriname', flag: '🇸🇷', timezone: 'America/Paramaribo'),
    Country(code: 'SJ', name: 'Svalbard and Jan Mayen', flag: '🇸🇯', timezone: 'Arctic/Longyearbyen'),
    Country(code: 'SZ', name: 'Swaziland', flag: '🇸🇿', timezone: 'Africa/Mbabane'),
    Country(code: 'SE', name: 'Sweden', flag: '🇸🇪', timezone: 'Europe/Stockholm'),
    Country(code: 'CH', name: 'Switzerland', flag: '🇨🇭', timezone: 'Europe/Zurich'),
    Country(code: 'SY', name: 'Syrian Arab Republic', flag: '🇸🇾', timezone: 'Asia/Damascus'),
    Country(code: 'TW', name: 'Taiwan, Province of China', flag: '🇹🇼', timezone: 'Asia/Taipei'),
    Country(code: 'TJ', name: 'Tajikistan', flag: '🇹🇯', timezone: 'Asia/Dushanbe'),
    Country(code: 'TZ', name: 'Tanzania, United Republic of', flag: '🇹🇿', timezone: 'Africa/Dar_es_Salaam'),
    Country(code: 'TH', name: 'Thailand', flag: '🇹🇭', timezone: 'Asia/Bangkok'),
    Country(code: 'TL', name: 'Timor-Leste', flag: '🇹🇱', timezone: 'Asia/Dili'),
    Country(code: 'TG', name: 'Togo', flag: '🇹🇬', timezone: 'Africa/Lome'),
    Country(code: 'TK', name: 'Tokelau', flag: '🇹🇰', timezone: 'Pacific/Fakaofo'),
    Country(code: 'TO', name: 'Tonga', flag: '🇹🇴', timezone: 'Pacific/Tongatapu'),
    Country(code: 'TT', name: 'Trinidad and Tobago', flag: '🇹🇹', timezone: 'America/Port_of_Spain'),
    Country(code: 'TN', name: 'Tunisia', flag: '🇹🇳', timezone: 'Africa/Tunis'),
    Country(code: 'TR', name: 'Turkey', flag: '🇹🇷', timezone: 'Europe/Istanbul'),
    Country(code: 'TM', name: 'Turkmenistan', flag: '🇹🇲', timezone: 'Asia/Ashgabat'),
    Country(code: 'TC', name: 'Turks and Caicos Islands', flag: '🇹🇨', timezone: 'America/Grand_Turk'),
    Country(code: 'TV', name: 'Tuvalu', flag: '🇹🇻', timezone: 'Pacific/Funafuti'),
    Country(code: 'UG', name: 'Uganda', flag: '🇺🇬', timezone: 'Africa/Kampala'),
    Country(code: 'UA', name: 'Ukraine', flag: '🇺🇦', timezone: 'Europe/Kiev'),
    Country(code: 'AE', name: 'United Arab Emirates', flag: '🇦🇪', timezone: 'Asia/Dubai'),
    Country(code: 'GB', name: 'United Kingdom', flag: '🇬🇧', timezone: 'Europe/London'),
    Country(code: 'US', name: 'United States', flag: '🇺🇸', timezone: 'America/New_York'),
    Country(code: 'UY', name: 'Uruguay', flag: '🇺🇾', timezone: 'America/Montevideo'),
    Country(code: 'UZ', name: 'Uzbekistan', flag: '🇺🇿', timezone: 'Asia/Samarkand'),
    Country(code: 'VU', name: 'Vanuatu', flag: '🇻🇺', timezone: 'Pacific/Efate'),
    Country(code: 'VE', name: 'Venezuela', flag: '🇻🇪', timezone: 'America/Caracas'),
    Country(code: 'VN', name: 'Viet Nam', flag: '🇻🇳', timezone: 'Asia/Saigon'),
    Country(code: 'VG', name: 'Virgin Islands, British', flag: '🇻🇬', timezone: 'America/Tortola'),
    Country(code: 'VI', name: 'Virgin Islands, U.s.', flag: '🇻🇮', timezone: 'America/St_Thomas'),
    Country(code: 'WF', name: 'Wallis and Futuna', flag: '🇼🇫', timezone: 'Pacific/Wallis'),
    Country(code: 'EH', name: 'Western Sahara', flag: '🇪🇭', timezone: 'Africa/El_Aaiun'),
    Country(code: 'YE', name: 'Yemen', flag: '🇾🇪', timezone: 'Asia/Aden'),
    Country(code: 'ZM', name: 'Zambia', flag: '🇿🇲', timezone: 'Africa/Lusaka'),
    Country(code: 'ZW', name: 'Zimbabwe', flag: '🇿🇼', timezone: 'Africa/Harare'),
  ];
}
